<?php

require 'inc/bootstrap.php';
App::getAuth();
$db = App::getDatabase();
$auth = App::getAuth();
$auth->connectFromCookie($db);



if (!empty($_POST)){
    if (empty($_POST['password']) || $_POST['password'] != $_POST['password_confirm']){
        $_SESSION['flash']['danger'] = "Les mots de passe de correspondent pas";
    } else {
        $user_id = $_SESSION['auth']->id;
        $password = password_hash($_POST['password'], PASSWORD_BCRYPT);

        $db->query('UPDATE users SET password = ? WHERE id = ?', [$password, $user_id]);
        $_SESSION['flash']['success'] = "Votre mot de passe a bien été mis à jour ";
    }
}

$user_id = $_SESSION['auth']->id;
$commandes = $db->query('SELECT id, mydate, quantite, montant, id_user  FROM commandes WHERE id_user = "'.$user_id.'" ORDER BY mydate DESC');
$commandes = $commandes->fetchAll(PDO::FETCH_ASSOC);

require 'inc/header.phtml';
?>
<main>
    <h1>Bonjour <?= $_SESSION['auth']->civility?> <?= $_SESSION['auth']->lastname?></h1>

    <form action="" method="POST" class="reset form_style">
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Entrer votre nouveau mot de passe">
        </div>

        <div class="form-group">
            <input class="form-control" type="password" name="password_confirm" placeholder="Confirmer votre nouveau mot de passe">
        </div>

        <button class="button -green center">Changer mon mot de passe</button>
    </form>

    <h3>Historique de vos commandes</h3>
    <table class="allcommandes">
        <thead>
        <tr>
            <th>Date de commande</th>
            <th>Quantité</th>
            <th>Montant</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($commandes as $iK => $aValues){
            ?>
            <tr>
                <td><?=$aValues['mydate']; ?></td>
                <td><?=$aValues['quantite']; ?></td>
                <td><?=$aValues['montant']; ?> €</td>
            </tr>
            <?php
        }
        ?>
        </tbody>
    </table>

</main>

<?php
include ('inc/footer.phtml');