<?php
require ('inc/bootstrap.php');

if (isset($_GET['id']) && isset($_GET['token'])){
    $auth = App::getAuth();
    $db = App::getDatabase();
    $user = $auth->checkResetTocken($db, $_GET['id'], $_GET['token']);


           if ($user){
                if (!empty($_POST)){
                    $validator = new Validator($_POST);
                    $validator->isAlpha($password);
                    if ($validator->isValid()){
                        $password = $auth->hashPassword($_POST['password']);
                        $db->query('UPDATE users SET password = ?, reset_at = NULL, reset_token = NULL WHERE id = ?', [$password], $_GET['id']);
                        $auth->connect($user);
                        Session::getInstance()->setFlash('success','Votre mot de passe a bien été modifié');
                        App::redirect('account.phtml');
                    }
                }

           }else{
               Session::getInstance()->setFlash('danger','Ce token n\'est pas valide');
               App::redirect('login.phtml');
           }

    }else {
        App::redirect('login.phtml');
}

include ('inc/header.phtml');
?>

    <main>


        <h1>Réinitialiser mon mot de passe</h1>


        <form method="post" action="">

            <div class="form-group">
                <label for="password">Votre mot de passe</label>
                <input type="password" name="password" id="password" class="form-control" />
            </div>

            <div class="form-group">
                <label for="password">Confirmez votre mot de passe</label>
                <input type="password" name="password_confirm" id="password" class="form-control" />
            </div>

            <button type="submit" class="btn btn-success">Réinitialiser mon mot de passe</button>

            <p><a href="http://localhost/coque/signin.phtml">Pas encore inscrit ? Cliquez ici</a> </p>

        </form>
    </main>
<?php
include ('inc/footer.phtml');