     <footer>
         <nav>
             <a href="/index.php">Accueil</a>
             <a href="/index.php">Notre histoire</a>
             <a href="/index.php">Nos projets</a>
             <a href="/index.php">Contact</a>
         </nav>
     </footer>
    </body>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     <script src="assets/js/script.js"></script>
     </html>
